/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculadora.Telas;

import calculadora.Operacoes;
import java.awt.event.ActionEvent;

/**
 *
 * @author Vinicius
 */
public class Frontal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Frontal.class.getName());
        
    double resultado = 0;
    double n1;
    double n2;
    String Visor ="Ola seja bem vindo";
    String operacoes = "";
    Operacoes o = new Operacoes();
    public Frontal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btndiv = new javax.swing.JButton();
        btnmais = new javax.swing.JButton();
        btnmenos = new javax.swing.JButton();
        btnvezes = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        txtVisor = new javax.swing.JTextField();
        btnigual = new javax.swing.JButton();
        btnzera = new javax.swing.JButton();
        btnponto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jButton7.setText("jButton1");

        jButton1.setText("=");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        btn1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn1.setText("1");
        btn1.addActionListener(this::btn1ActionPerformed);

        btn2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn2.setText("2");
        btn2.addActionListener(this::btn2ActionPerformed);

        btn3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn3.setText("3");
        btn3.addActionListener(this::btn3ActionPerformed);

        btn4.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn4.setText("4");
        btn4.addActionListener(this::btn4ActionPerformed);

        btn5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn5.setText("5");
        btn5.addActionListener(this::btn5ActionPerformed);

        btn6.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn6.setText("6");
        btn6.addActionListener(this::btn6ActionPerformed);

        btn7.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn7.setText("7");
        btn7.addActionListener(this::btn7ActionPerformed);

        btn8.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn8.setText("8");
        btn8.addActionListener(this::btn8ActionPerformed);

        btn9.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn9.setText("9");
        btn9.addActionListener(this::btn9ActionPerformed);

        btndiv.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btndiv.setText("/");
        btndiv.addActionListener(this::btndivActionPerformed);

        btnmais.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnmais.setText("+");
        btnmais.addActionListener(this::btnmaisActionPerformed);

        btnmenos.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnmenos.setText("-");
        btnmenos.addActionListener(this::btnmenosActionPerformed);

        btnvezes.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnvezes.setText("x");
        btnvezes.addActionListener(this::btnvezesActionPerformed);

        btn0.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btn0.setText("0");
        btn0.addActionListener(this::btn0ActionPerformed);

        txtVisor.setEditable(false);
        txtVisor.setFont(new java.awt.Font("Tempus Sans ITC", 3, 18)); // NOI18N
        txtVisor.addActionListener(this::txtVisorActionPerformed);

        btnigual.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnigual.setText("=");
        btnigual.addActionListener(this::btnigualActionPerformed);

        btnzera.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnzera.setText("AC");
        btnzera.addActionListener(this::btnzeraActionPerformed);

        btnponto.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        btnponto.setText(".");
        btnponto.addActionListener(this::btnpontoActionPerformed);

        jLabel1.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel1.setText("Seja Bem Vindo ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn3)
                                    .addComponent(btn0))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnigual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(btn6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btn9)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btndiv)
                                    .addComponent(btnvezes)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmais)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnzera, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnmenos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnponto)))
                        .addContainerGap(26, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtVisor)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtVisor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn4)
                    .addComponent(btn7)
                    .addComponent(btnmais)
                    .addComponent(btn1)
                    .addComponent(btnzera))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn2)
                    .addComponent(btn5)
                    .addComponent(btn8)
                    .addComponent(btnmenos)
                    .addComponent(btnponto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn3)
                    .addComponent(btn6)
                    .addComponent(btn9)
                    .addComponent(btnvezes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn0)
                    .addComponent(btnigual)
                    .addComponent(btndiv))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        
             txtVisor.setText(txtVisor.getText() + 1);  
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        txtVisor.setText(txtVisor.getText() + 2);  
    
    }//GEN-LAST:event_btn2ActionPerformed

    private void txtVisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVisorActionPerformed
    }//GEN-LAST:event_txtVisorActionPerformed

    private void btnmaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmaisActionPerformed
       n1 =  Double.parseDouble(txtVisor.getText());
       
       operacoes = "+";
       
       txtVisor.setText("");
    }//GEN-LAST:event_btnmaisActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        txtVisor.setText(txtVisor.getText() + 3);  
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
txtVisor.setText(txtVisor.getText() + 4);          // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
txtVisor.setText(txtVisor.getText() + 5);          // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
  txtVisor.setText(txtVisor.getText() + 6);  
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
   txtVisor.setText(txtVisor.getText() + 7);  
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
   txtVisor.setText(txtVisor.getText() + 8);  
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
      txtVisor.setText(txtVisor.getText() + 9);  
    }//GEN-LAST:event_btn9ActionPerformed

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        n2 =  Double.parseDouble(txtVisor.getText());
        
        
        
       switch (operacoes) {
    case "+":
       resultado =  o.soma(n1, n2);
        break;
    case "-":
       resultado =  o.Sub(n1, n2);
        break;
    case "*":
       resultado =  o.multi(n1, n2);
        break;
    case "/":
        if (n2!= 0) {
            resultado =n1 / n2;
        } else {
            txtVisor.setText("Erro"); // Tratamento simples para não quebrar
            return; 
        }
        break;
} 
        
        txtVisor.setText(String.format("%.4f", resultado));
        
        
    }//GEN-LAST:event_btnigualActionPerformed

    private void btnmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenosActionPerformed
 n1 =  Double.parseDouble(txtVisor.getText());
       
       operacoes = "-";
       
       txtVisor.setText("");
    }//GEN-LAST:event_btnmenosActionPerformed

    private void btnvezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnvezesActionPerformed
       n1 = Double.parseDouble(txtVisor.getText());
       
       operacoes = "*";
       
       txtVisor.setText("");
    }//GEN-LAST:event_btnvezesActionPerformed

    private void btndivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndivActionPerformed
       n1 =  Double.parseDouble(txtVisor.getText());
       
       operacoes = "/";
       
       txtVisor.setText("");
    }//GEN-LAST:event_btndivActionPerformed

    private void btnzeraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnzeraActionPerformed
        txtVisor.setText("");
    }//GEN-LAST:event_btnzeraActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        txtVisor.setText(txtVisor.getText() + 0);  
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnpontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpontoActionPerformed
      txtVisor.setText(txtVisor.getText() + ".");
    }//GEN-LAST:event_btnpontoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Frontal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btndiv;
    private javax.swing.JButton btnigual;
    private javax.swing.JButton btnmais;
    private javax.swing.JButton btnmenos;
    private javax.swing.JButton btnponto;
    private javax.swing.JButton btnvezes;
    private javax.swing.JButton btnzera;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtVisor;
    // End of variables declaration//GEN-END:variables
}
